<a href="https://colab.research.google.com/github/alelom/Notebooks/blob/master/Statistical%20Learning/Pytorch/Exercise%20Files/Autograd_with_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

In [1]:
import torch

In [16]:
tensor = torch.randn(4,3) # matrix from normal distribution

In [17]:
tensor.requires_grad_(True) # always calculate the gradient for this tensor, updating it every time it's modified, and store it in the same tensor object.

tensor([[ 0.1698, -0.3622, -0.8116],
        [-0.4120, -0.9719,  0.7049],
        [-2.0413,  0.4612, -0.1069],
        [-0.7725, -1.6714,  1.6946]], requires_grad=True)

In [40]:
print(tensor.grad_fn) # None, why?
print(tensor.grad)

None
None


In [41]:
# If we create a new tensor based on the first, it will keep the requires_grad setting: the new gradient will already be there.
y = torch.exp(tensor) # a new tensor y = e^tensor
print(y) 

tensor([[1.1851, 0.6961, 0.4442],
        [0.6623, 0.3784, 2.0236],
        [0.1299, 1.5861, 0.8986],
        [0.4618, 0.1880, 5.4443]], grad_fn=<ExpBackward>)


In [46]:
print(y.grad_fn)  # ExpBackward object
print(y.grad)     # None
# UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. 
# Its .grad attribute won't be populated during autograd.backward(). 
# If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor.
# If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. 
# See github.com/pytorch/pytorch/pull/30531 for more information.

None


/usr/local/lib/python3.6/dist-packages/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [47]:
# operation to get a scalar value from the second tensor y
scalarValue = y.mean()
scalarValue

tensor(1.1749, grad_fn=<MeanBackward0>)

In [48]:
# In order to get the gradient of the first tensor, we need to do a backward pass.
scalarValue.backward() # backward pass from this last tensor to the very first one.

In [52]:
# now the first tensor has the gradient value:
print(tensor.grad)    # this now has values.
print(tensor.grad_fn) # still no gradient function.

tensor([[0.0988, 0.0580, 0.0370],
        [0.0552, 0.0315, 0.1686],
        [0.0108, 0.1322, 0.0749],
        [0.0385, 0.0157, 0.4537]])
None


## Detaching a tensor from grad

In [53]:
tensor.detach() # the gradient for this tensor will not be updated??

tensor([[ 0.1698, -0.3622, -0.8116],
        [-0.4120, -0.9719,  0.7049],
        [-2.0413,  0.4612, -0.1069],
        [-0.7725, -1.6714,  1.6946]])

In [55]:
# When you want to evaluate a model, sometimes you might want to prevent tracking history;
# this because that model might have trainable parameters. 
# I.e. you have requires_grad set to True for the model,
# but for whatever reason you don't want the gradient calculated, and simply want the output.

print(scalarValue.requires_grad) # this is True

with torch.no_grad():
  scalarValue = y.mean()

print(scalarValue) # this does not have 'grad_fn=<MeanBackward0>' anymore
print(scalarValue.requires_grad) # this is now False.

True
tensor(1.1749)
False
