# Chapter 4 - Matrix decompositions

In [17]:
import numpy as np
from scipy import linalg #https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html

In [10]:
A = np.array([[4,1],[2,3]])
A

array([[4, 1],
       [2, 3]])

In [19]:
linalg.eigvals(A) # only eigenvalues

array([5.+0.j, 2.+0.j])

In [23]:
linalg.eig(A) #eigenvalues and eigenvectors(?)
# see https://www.wolframalpha.com/input/?i=eigenvectors+%7B%7B4%2C2%7D%2C%7B1%2C3%7D%7D

(array([5.+0.j, 2.+0.j]), array([[ 0.70710678, -0.4472136 ],
        [ 0.70710678,  0.89442719]]))