# Chapter 2 - Matrices

In [29]:
import numpy as np
from scipy import linalg

### 2.2.2 Inverse and transpose

In [24]:
 A = np.array([[4,1],[2,3]])
A

array([[4, 1],
       [2, 3]])

#### Inverse

In [25]:
linalg.inv(A)

array([[ 0.3, -0.1],
       [-0.2,  0.4]])

#### Transpose

In [26]:
np.transpose(A)

array([[4, 2],
       [1, 3]])

In [30]:
B = A*np.transpose(A)

In [31]:
def check_symmetric(a, rtol=1e-05, atol=1e-08):
    return np.allclose(a, a.T, rtol=rtol, atol=atol)

In [32]:
check_symmetric(B)

True

### 2.7 Linear mappings

#### Kernel

In [35]:
A = np.array([[1, 1], [1, 1]])
linalg.null_space(A)

array([[ 0.70710678],
       [-0.70710678]])

In [41]:
np.array([[ 0.70710678],
       [-0.70710678]])

array([[ 0.70710678],
       [-0.70710678]])